### ISSUE TITLE
Panic invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by HugoPoi** [mr-karan/doggo#11] opened 2020-12-28 16:31 UTC
crash with `docker run ghcr.io/mr-karan/doggo:v0.2.0 thepiratebay.org @https://doh.franciliens.net`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x710ca6]

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Logger).newEntry(0x0, 0xc0000938c8)
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/logger.go:96 +0x26
github.com/sirupsen/logrus.(*Logger).WithFields(0x0, 0xc000093a20, 0x0)
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/logger.go:121 +0x4a
github.com/mr-karan/doggo/pkg/resolvers.(*DOHResolver).Lookup(0xc0000ca230, 0x7fff6738ef58, 0x10, 0x10001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/doggo/doggo/pkg/resolvers/doh.go:51 +0x679
main.main()
	/home/runner/work/doggo/doggo/cmd/doggo/cli.go:134 +0xbb3
```

**Comment by mr-karan** [comment] 2020-12-29 03:52
@HugoPoi  Thanks for reporting this. Looks like a regression in DOH resolver from v0.2.

Fixed in https://github.com/mr-karan/doggo/commit/250591098b3a178d527a65a8ef9dc0a971b59ea6

And released [v0.2.1](https://github.com/mr-karan/doggo/releases/tag/v0.2.1)

```
docker run ghcr.io/mr-karan/doggo:v0.2.1 thepiratebay.org @https://cloudflare-dns.com/dns-query   
NAME             	TYPE	CLASS	TTL	ADDRESS      	NAMESERVER                           
thepiratebay.org.	A   	IN   	15s	162.159.137.6	https://cloudflare-dns.com/dns-query	
thepiratebay.org.	A   	IN   	15s	162.159.136.6	https://cloudflare-dns.com/dns-query	
```

Feel free to reopen in case issue persists.

**Closed by mr-karan** 2020-12-29 03:52 UTC
