### ISSUE TITLE
Docker doggo-web  doh query

### ISSUE THREAD

**Issue by gkl1368** [mr-karan/doggo#132] opened 2024-07-02 13:02 UTC
when query dns use doh like [https](https://cloudflare-dns.com/dns-query) in docker doggo-web, it shows error: tls: failed to verify certificate: x509: certificate signed by unknown authority". but it works ok when I run doggo-web.bin in the host.

**Comment by gkl1368** [comment] 2024-07-02 16:48
I use this docker: ghcr.io/mr-karan/doggo-web:latest
time=2024-07-02T16:47:22.735Z level=ERROR msg="error in lookup" error="Post \"https://cloudflare-dns.com/dns-query\": tls: failed to verify certificate: x509: certificate signed by unknown authority"

**Comment by mr-karan** [comment] 2024-07-03 03:51
```
docker run --rm ghcr.io/mr-karan/doggo:latest  mrkaran.dev @https://cloudflare-dns.com/dns-query --short

104.21.7.168
172.67.187.239
```

This did work, however I noticed the container doesn't have `ca-certificates` and it might likely be because of that. Just wondering why I am unable to reproduce it. I'll push `ca-certificates` in the next release and you can try with that.

**Comment by gkl1368** [comment] 2024-07-03 07:02
I have add this line in web.Dockerfile
RUN apt update && apt install -y ca-certificates && update-ca
-certificates
and rebuild the image. Now it works fine.

**Comment by mr-karan** [comment] 2024-07-03 11:01
Thanks. I'll be pushing a fix for this in the next version

**Closed** 2024-07-03 16:37 UTC
